## Задание 1.3.1

Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [2]:
import numpy as np

matrix = np.full(64, 0).reshape(8, 8)

for i in range(8):
  for j in range(8):
    if (i % 2 != 0 and j % 2 == 0) or (i % 2 == 0 and j % 2 != 0):
      matrix[i][j] = 1

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Задание 1.3.2

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange

In [ ]:
matrix = np.zeros(shape=(5, 5))
matrix += np.arange(5)

print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Задание 1.3.3

Создать массив 3x3x3 со случайными значениями.

In [ ]:
print(np.random.random(size=(3, 3, 3)))

[[[0.3979532  0.88965343 0.42579973]
  [0.92421394 0.51011869 0.18473728]
  [0.22476048 0.24540347 0.45365308]]

 [[0.79723086 0.25039728 0.51568438]
  [0.17601159 0.19757778 0.45834375]
  [0.60194784 0.09973986 0.47828216]]

 [[0.12546043 0.68433244 0.49695507]
  [0.05772747 0.28323213 0.47419217]
  [0.70052032 0.15648053 0.07898696]]]


## Задание 1.3.4

Создать матрицу с 0 внутри, и 1 на границах.

In [3]:
matrix = np.ones(shape=(10, 10))

for i in range(len(matrix)):
  for j in range(len(matrix[i])):
    if (i > 0 and i < len(matrix) - 1) and (j > 0 and j < len(matrix[i]) - 1):
        matrix[i][j] = 0

print(matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Задание 1.3.5

Создайте массив и отсортируйте его по убыванию.

In [ ]:
arr = np.arange(10)
print(np.sort(arr)[::-1])

[9 8 7 6 5 4 3 2 1 0]


## Задание 1.3.6

Создайте матрицу, выведите ее форму, размер и размерность.

In [ ]:
matrix = np.zeros(shape=(10, 10))
matrix += np.arange(10)

print('Форма:', matrix.shape, '\nРазмер:', matrix.size, '\nРазмерность:', matrix.ndim)

Форма: (10, 10) 
Размер: 100 
Размерность: 2


## Задание 2.3.1

Найдите евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу.

In [ ]:
import pandas as pd

arr1 = pd.Series([3, 2, 3])
arr2 = pd.Series([6, 0, 5])

print((sum(arr1 - arr2) ** 2) ** 0.5)

3.0


## Задание 2.3.2

In [ ]:
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/WorldDBTables/CountryTable.csv'

dataframe = pd.read_csv(url)
dataframe

code          name      continent                     region  \
0    ABW         Aruba  North America                  Caribbean   
1    AFG   Afghanistan           Asia  Southern and Central Asia   
2    AGO        Angola         Africa             Central Africa   
3    AIA      Anguilla  North America                  Caribbean   
4    ALB       Albania         Europe            Southern Europe   
..   ...           ...            ...                        ...   
234  YEM         Yemen           Asia                Middle East   
235  YuG    Yugoslavia         Europe            Southern Europe   
236  ZAF  South Africa         Africa            Southern Africa   
237  ZMB        Zambia         Africa             Eastern Africa   
238  ZWE      Zimbabwe         Africa             Eastern Africa   

     surface_area independence_year  population life_expectancy       gnp  \
0           193.0              NuLL      103000            78.4     828.0   
1        652090.0              1919    22720000            45.9    5976.0   
2       1246700.0              1975    12878000            38.3    6648.0   
3            96.0              NuLL        8000            76.1      63.2   
4         28748.0              1912     3401200            71.6    3205.0   
..            ...               ...         ...             ...       ...   
234      527968.0              1918    18112000            59.8    6041.0   
235      102173.0              1918    10640000            72.4   17000.0   
236     1221037.0              1910    40377000            51.1  116729.0   
237      752618.0              1964     9169000            37.2    3377.0   
238      390757.0              1980    11669000            37.8    5951.0   

    gnp_old             local_name  \
0       793                  Aruba   
1      NuLL  Afganistan/Afqanestan   
2      7984                 Angola   
3      NuLL               Anguilla   
4      2500              Shqiperia   
..      ...                    ...   
234    5729               Al-Yaman   
235    NuLL            Jugoslavija   
236  129092           South Africa   
237    3922                 Zambia   
238    8670               Zimbabwe   

                                  government_form            head_of_state  \
0    Nonmetropolitan Territory of The Netherlands         Willem-Alexander   
1                                 Islamic Emirate            Mohammad Omar   
2                                        Republic  Jose Eduardo dos Santos   
3                   Dependent Territory of the uK             Elisabeth II   
4                                        Republic           Rexhep Mejdani   
..                                            ...                      ...   
234                                      Republic       Ali Abdallah Salih   
235                              Federal Republic       Vojislav KoStunica   
236                                      Republic              Thabo Mbeki   
237                                      Republic        Frederick Chiluba   
238                                      Republic         Robert G. Mugabe   

    capital code2  
0       129    AW  
1         1    AF  
2        56    AO  
3        62    AI  
4        34    AL  
..      ...   ...  
234    1780    YE  
235    1792    Yu  
236     716    ZA  
237    3162    ZM  
238    4068    ZW  

[239 rows x 15 columns]

## Задание 2.3.3

Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7.

In [ ]:
from IPython.display import display

display(dataframe.head(2))
print('\n')
display(dataframe.tail(3))
print('\n')
display(dataframe.shape)
print('\n')
display(dataframe.describe())
print('\n')
display(dataframe.iloc[1:4])
print('\n')
display(dataframe[dataframe['continent'] == 'Europe'].head(3))

code         name      continent                     region  surface_area  \
0  ABW        Aruba  North America                  Caribbean         193.0   
1  AFG  Afghanistan           Asia  Southern and Central Asia      652090.0   

  independence_year  population life_expectancy     gnp gnp_old  \
0              NuLL      103000            78.4   828.0     793   
1              1919    22720000            45.9  5976.0    NuLL   

              local_name                               government_form  \
0                  Aruba  Nonmetropolitan Territory of The Netherlands   
1  Afganistan/Afqanestan                               Islamic Emirate   

      head_of_state capital code2  
0  Willem-Alexander     129    AW  
1     Mohammad Omar       1    AF

code          name continent           region  surface_area  \
236  ZAF  South Africa    Africa  Southern Africa     1221037.0   
237  ZMB        Zambia    Africa   Eastern Africa      752618.0   
238  ZWE      Zimbabwe    Africa   Eastern Africa      390757.0   

    independence_year  population life_expectancy       gnp gnp_old  \
236              1910    40377000            51.1  116729.0  129092   
237              1964     9169000            37.2    3377.0    3922   
238              1980    11669000            37.8    5951.0    8670   

       local_name government_form      head_of_state capital code2  
236  South Africa        Republic        Thabo Mbeki     716    ZA  
237        Zambia        Republic  Frederick Chiluba    3162    ZM  
238      Zimbabwe        Republic   Robert G. Mugabe    4068    ZW

(239, 15)

surface_area    population           gnp
count  2.390000e+02  2.390000e+02  2.390000e+02
mean   6.232481e+05  2.543410e+07  1.228239e+05
std    1.924140e+06  1.093398e+08  6.379976e+05
min    4.000000e-01  0.000000e+00  0.000000e+00
25%    2.275000e+03  2.380000e+05  6.400000e+02
50%    7.174000e+04  3.869000e+06  4.787000e+03
75%    3.987545e+05  1.493550e+07  2.994450e+04
max    1.707540e+07  1.277558e+09  8.510700e+06

code         name      continent                     region  surface_area  \
1  AFG  Afghanistan           Asia  Southern and Central Asia      652090.0   
2  AGO       Angola         Africa             Central Africa     1246700.0   
3  AIA     Anguilla  North America                  Caribbean          96.0   

  independence_year  population life_expectancy     gnp gnp_old  \
1              1919    22720000            45.9  5976.0    NuLL   
2              1975    12878000            38.3  6648.0    7984   
3              NuLL        8000            76.1    63.2    NuLL   

              local_name                government_form  \
1  Afganistan/Afqanestan                Islamic Emirate   
2                 Angola                       Republic   
3               Anguilla  Dependent Territory of the uK   

             head_of_state capital code2  
1            Mohammad Omar       1    AF  
2  Jose Eduardo dos Santos      56    AO  
3             Elisabeth II      62    AI

code     name continent           region  surface_area independence_year  \
4   ALB  Albania    Europe  Southern Europe       28748.0              1912   
5   AND  Andorra    Europe  Southern Europe         468.0              1278   
15  AuT  Austria    Europe   Western Europe       83859.0              1918   

    population life_expectancy       gnp gnp_old  local_name  \
4      3401200            71.6    3205.0    2500   Shqiperia   
5        78000            83.5    1630.0    NuLL     Andorra   
15     8091800            77.7  211860.0  206025  osterreich   

                 government_form   head_of_state capital code2  
4                       Republic  Rexhep Mejdani      34    AL  
5   Parliamentary Coprincipality             NaN      55    AD  
15              Federal Republic  Thomas Klestil    1523    AT

## Задание 3.3.2

Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а второго (sepal_width_cm) с задействованием z-масштабирования.

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

scaler = MinMaxScaler()
st_scaler = StandardScaler()

dataframe = pd.read_csv('https://raw.githubusercontent.com/akmand/datasets/master/iris.csv')

dataframe[['sepal_length_cm']] = scaler.fit_transform(dataframe[['sepal_length_cm']])
dataframe[['sepal_width_cm']] = st_scaler.fit_transform(dataframe[['sepal_width_cm']])

dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]